apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-hello-world-chao
  labels:
    app: wordpress-hello-world-chao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-hello-world-chao
  template:
    metadata:
      labels:
        app: wordpress-hello-world-chao
    spec:
      containers:
        # CONTENEDOR 1: WORDPRESS
        - name: wordpress-hello-world-chao
          image: wordpress:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: wordpress-hello-world-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: wp-uploads
              mountPath: /var/www/html/wp-content/uploads
             
        # CONTENEDOR 2: MYSQL
        - name: mysql
          image: mysql:5.7
          env:
            - name: WORDPRESS_DB_HOST
              value: "127.0.0.1"
          envFrom:
            - secretRef:
                name: wordpress-hello-world-secret
          resources: # <--- Ahora estÃ¡ bien alineado
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: wp-uploads
          persistentVolumeClaim:
            claimName: wordpress-uploads-pvc