apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-hello-world-chao
  labels:
    app: wordpress-hello-world-chao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-hello-world-chao
  template:
    metadata:
      labels:
        app: wordpress-hello-world-chao
    spec:
      containers:
        - name: wordpress-hello-world-chao
          image: chao/wordpress:v2
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: wordpress-hello-world-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: wp-uploads
              mountPath: /var/www/html/wp-content/uploads
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5; cp -rp /var/www/staging/. /var/www/html/"]
        

        - name: mysql
          image: mysql:5.7
          env:
            - name: WORDPRESS_DB_HOST
              value: "127.0.0.1"
          envFrom:
            - secretRef:
                name: wordpress-hello-world-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: wp-uploads
          persistentVolumeClaim:
            claimName: wordpress-uploads-pvc