#file: noinspection HttpUrlsUsage
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: academic-configurations-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  rules:
    - host: wordpress-hello-world-chao.ctdesarrollo.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-hello-world-chao
                port:
                  number: 8080
