#file: noinspection HttpUrlsUsage
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: academic-configurations-gateway-ingress
  namespace: web-presence-{BUILD_ENV}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  tls:
    - hosts:
        - wordpress-hello-world.ctdesarrollo.org
      secretName: wildcard-ctdesarrollo-org
  rules:
    - host: wordpress-hello-world.ctdesarrollo.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-hello-world
                port:
                  number: 8080
