apiVersion: v1
kind: Service
metadata:
  name: wordpress-hello-world
  namespace: web-presence-{BUILD_ENV}
  labels:
    app: wordpress-hello-world
spec:
  type: LoadBalancer
  selector:
    app: wordpress-hello-world
  sessionAffinity: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 32080

#http: microk8s.kubectl port-forward service/wordpress-hello-world -n web-presence-{BUILD_ENV} 80:8080 --address '0.0.0.0'
